name: Compile Typst

on:
    push:
        branches:
            - main
        # Only run when a .typ file is changed
        paths:
            - "**/*.typ"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Typst
              uses: cestef/setup-typst@main
            - name: Find all typst files # structure: <course>/**/main.typ
              run: echo "stdout=$(find . -name 'main.typ' | tr '\n' ' ')" >> $GITHUB_OUTPUT
              id: find_files
            - name: Compile all files
              run: |
                  ROOT_DIR=$(pwd)
                  for file in ${{ steps.find_files.outputs.stdout }}; do
                      pdf_file=$(echo $file | sed 's/\.typ$/.pdf/')
                      echo "Compiling $file to $pdf_file"
                      typst compile $file $pdf_file --root $ROOT_DIR
                  done
              shell: bash
              id: compile
            - name: Add pdfs to `pdfs` directory
              run: |
                  mkdir -p pdfs
                  pdfs=$(find . -name 'main.pdf')
                  for pdf in $pdfs; do
                      course=$(dirname $pdf | cut -d'/' -f2)
                      echo "Copying $pdf to pdfs/$course.pdf"
                      cp $pdf pdfs/$course.pdf
                  done
              shell: bash
            - name: Commit and push pdfs
              run: |
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  git add pdfs
                  git commit -m "Update compiled pdfs"
                  git push
              shell: bash
